In [ ]:
# Boxcox and PKL generate of "Date" and "Numeric".

In [27]:
import sys
import time
import numpy as np
import pandas as pd
from scipy.stats import skew, boxcox
from sklearn.preprocessing import StandardScaler
#from pandas.core.common import array_equivalent
import pickle

In [28]:
def duplicate_columns(frame):
    groups = frame.columns.to_series().groupby(frame.dtypes).groups
    dups = []

    for t, v in groups.items():

        cs = frame[v].columns
        vs = frame[v]
        lcs = len(cs)

        for i in range(lcs):
            ia = vs.iloc[:,i].values
            for j in range(i+1, lcs):
                ja = vs.iloc[:,j].values
                if np.array_equal(ia, ja):
                    dups.append(cs[i])
                    break

    return dups

In [ ]:
dups = duplicate_columns(train_test)

In [29]:
def scale_data(X, scaler=None):
    if not scaler:
        scaler = StandardScaler()
        scaler.fit(X)
    X = scaler.transform(X)
    return X, scaler

In [30]:
train = pd.read_csv("D:/Project/Sample data/Sam_8/train_date.csv", index_col=0)
test = pd.read_csv("D:/Project/Sample data/Sam_Test_8/test_date.csv", index_col=0)
train_test = pd.concat([train, test])
print('Concatenation OK!')
print(train_test.shape)
ntrain = train.shape[0]
ntest = test.shape[0]
del(test, train)

Concatenation OK!
(16000, 1156)

In [31]:

dups = duplicate_columns(train_test)
train_test = train_test.drop(dups, axis=1)
print('Unduplication OK!')
print(train_test.shape)

Unduplication OK!
(16000, 1156)

In [32]:
skewed_feats = train_test.apply(lambda x: skew(x.dropna()))
skewed_feats = skewed_feats[np.absolute(skewed_feats) > 0.3]
print(skewed_feats)
skewed_feats = skewed_feats.index
for feats in skewed_feats:
        train_test[feats] = train_test[feats] + 1.1
        train_test[feats], lam = boxcox(train_test[feats])
print('Boxcox is sucessfull!')
x_train = train_test.iloc[:ntrain, :]
x_test = train_test.iloc[ntrain:, :]
train_test_scaled, scaler = scale_data(train_test.fillna(0))
train, _ = scale_data(x_train.fillna(0), scaler)
test, _ = scale_data(x_test.fillna(0), scaler)
print('Data is scaled!')

L1_S24_D677     0.433285
L1_S24_D681     0.433285
L1_S24_D685     0.433285
L1_S24_D689     0.433285
L1_S24_D693     0.433285
L1_S24_D697     1.229301
L1_S24_D702     0.431604
L1_S24_D707     0.431604
L1_S24_D712     0.431604
L1_S24_D716     1.229301
L1_S24_D721     1.229301
L1_S24_D725     0.431604
L1_S24_D730     0.431604
L1_S24_D735     0.431604
L1_S24_D739     0.431604
L1_S24_D743     0.431604
L1_S24_D748     1.229301
L1_S24_D753     1.229301
L1_S24_D758     1.229301
L1_S24_D763     1.229301
L1_S24_D768     1.229301
L1_S24_D772     0.430656
L1_S24_D777     1.229301
L1_S24_D782     1.229301
L1_S24_D787     1.229301
L1_S24_D792     1.229301
L1_S24_D797     1.229301
L1_S24_D801     0.433283
L1_S24_D804     0.433290
L1_S24_D807     0.433276
                  ...
L3_S47_D4175   -0.426922
L3_S47_D4180   -0.426922
L3_S47_D4185   -0.426922
L3_S47_D4190   -0.426922
L3_S48_D4194   -0.426923
L3_S48_D4195   -0.426923
L3_S48_D4197   -0.426923
L3_S48_D4199   -0.426923
L3_S48_D4201   -0.426923
L3_S48_D4203   -0.426923
L3_S48_D4205   -0.426923
L3_S49_D4208   -0.362484
L3_S49_D4213   -0.362484
L3_S49_D4218   -0.362484
L3_S49_D4223   -0.362484
L3_S49_D4228   -0.362484
L3_S49_D4233   -0.362484
L3_S49_D4238   -0.362484
L3_S50_D4242   -0.494569
L3_S50_D4244   -0.494569
L3_S50_D4246   -0.494569
L3_S50_D4248   -0.494569
L3_S50_D4250   -0.494569
L3_S50_D4252   -0.494569
L3_S50_D4254   -0.494569
L3_S51_D4255   -0.426911
L3_S51_D4257   -0.426911
L3_S51_D4259   -0.426911
L3_S51_D4261   -0.426911
L3_S51_D4263   -0.426911
Length: 598, dtype: float64

C:\Users\Rezaul Abedin\Anaconda3\lib\site-packages\scipy\stats\morestats.py:1031: RuntimeWarning: invalid value encountered in less_equal
  if any(x <= 0):

Boxcox is sucessfull!
Data is scaled!

In [33]:
train_ids = x_train.index
test_ids = x_test.index
col_train = x_train.columns
col_test = x_test.columns
train_df = pd.DataFrame(data=train, index=train_ids, columns=col_train)
test_df = pd.DataFrame(data=test, index=test_ids, columns=col_test)

In [40]:
test_df.head(5)

,L0_S0_D1,L0_S0_D3,L0_S0_D5,L0_S0_D7,L0_S0_D9,L0_S0_D11,L0_S0_D13,L0_S0_D15,L0_S0_D17,L0_S0_D19,...,L3_S50_D4246,L3_S50_D4248,L3_S50_D4250,L3_S50_D4252,L3_S50_D4254,L3_S51_D4255,L3_S51_D4257,L3_S51_D4259,L3_S51_D4261,L3_S51_D4263
Id,,,,,,,,,,,,,,,,,,,,,
164,-0.864015,-0.864015,-0.864015,-0.864015,-0.864015,-0.864015,-0.864015,-0.864015,-0.864015,-0.864015,...,-0.115878,-0.115878,-0.115878,-0.115878,-0.115878,-0.161564,-0.161564,-0.161564,-0.161564,-0.161564
640,0.056041,0.056041,0.056041,0.056041,0.056041,0.056041,0.056041,0.056041,0.056041,0.056041,...,-0.115878,-0.115878,-0.115878,-0.115878,-0.115878,-0.161564,-0.161564,-0.161564,-0.161564,-0.161564
710,1.063661,1.063661,1.063661,1.063661,1.063661,1.063661,1.063661,1.063661,1.063661,1.063661,...,-0.115878,-0.115878,-0.115878,-0.115878,-0.115878,-0.161564,-0.161564,-0.161564,-0.161564,-0.161564
778,0.113568,0.113568,0.113568,0.113568,0.113568,0.113568,0.113568,0.113568,0.113568,0.113568,...,-0.115878,-0.115878,-0.115878,-0.115878,-0.115878,-0.161564,-0.161564,-0.161564,-0.161564,-0.161564
878,-0.864015,-0.864015,-0.864015,-0.864015,-0.864015,-0.864015,-0.864015,-0.864015,-0.864015,-0.864015,...,-0.115878,-0.115878,-0.115878,-0.115878,-0.115878,-0.161564,-0.161564,-0.161564,-0.161564,-0.161564

In [35]:
#train_df.to_csv('D:/Project/Sample data/train_date_df/train_date_df.csv')

In [36]:
#train_df.to_pickle('D:/Project/Sample data/train_date_df/train_date_df.pkl')
#test_df.to_pickle('D:/Project/Sample data/test_date_df/test_date_df.pkl')

In [37]:
train_df=train_df.round(5)

In [43]:
test_df=test_df.round(5)

In [44]:
test_df.head(5)

,L0_S0_D1,L0_S0_D3,L0_S0_D5,L0_S0_D7,L0_S0_D9,L0_S0_D11,L0_S0_D13,L0_S0_D15,L0_S0_D17,L0_S0_D19,...,L3_S50_D4246,L3_S50_D4248,L3_S50_D4250,L3_S50_D4252,L3_S50_D4254,L3_S51_D4255,L3_S51_D4257,L3_S51_D4259,L3_S51_D4261,L3_S51_D4263
Id,,,,,,,,,,,,,,,,,,,,,
164,-0.86401,-0.86401,-0.86401,-0.86401,-0.86401,-0.86401,-0.86401,-0.86401,-0.86401,-0.86401,...,-0.11588,-0.11588,-0.11588,-0.11588,-0.11588,-0.16156,-0.16156,-0.16156,-0.16156,-0.16156
640,0.05604,0.05604,0.05604,0.05604,0.05604,0.05604,0.05604,0.05604,0.05604,0.05604,...,-0.11588,-0.11588,-0.11588,-0.11588,-0.11588,-0.16156,-0.16156,-0.16156,-0.16156,-0.16156
710,1.06366,1.06366,1.06366,1.06366,1.06366,1.06366,1.06366,1.06366,1.06366,1.06366,...,-0.11588,-0.11588,-0.11588,-0.11588,-0.11588,-0.16156,-0.16156,-0.16156,-0.16156,-0.16156
778,0.11357,0.11357,0.11357,0.11357,0.11357,0.11357,0.11357,0.11357,0.11357,0.11357,...,-0.11588,-0.11588,-0.11588,-0.11588,-0.11588,-0.16156,-0.16156,-0.16156,-0.16156,-0.16156
878,-0.86401,-0.86401,-0.86401,-0.86401,-0.86401,-0.86401,-0.86401,-0.86401,-0.86401,-0.86401,...,-0.11588,-0.11588,-0.11588,-0.11588,-0.11588,-0.16156,-0.16156,-0.16156,-0.16156,-0.16156

In [47]:
train_df.to_csv('D:/Project/Sample data/train_date_df/train_date_df.csv')

In [ ]:
test_df.to_csv('D:/Project/Sample data/train_date_df/test_date_df.csv')